name: "KiCad CI/CD for ZK-meter"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    paths:
      - 'pcb/*.kicad_sch'
      - 'pcb/*.kicad_pcb'
      - 'pcb/*.kicad_pro'
      - '**/*kibot.yml'
  pull_request:
    paths:
      - 'pcb/*.kicad_sch'
      - 'pcb/*.kicad_pcb'
      - 'pcb/*.kicad_pro'
      - '**/*kibot.yml'
  repository_dispatch:
    types: [run_qs]

env:
  schema: "pcb/main_pcb.kicad_sch"
  board: "pcb/main_pcb.kicad_pcb"
  dir: .

jobs:
# checks
  ERC:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad7_auto_full:latest
    steps:
      - uses: actions/checkout@v3
      - name: run kibot
        run: |
          kibot -c kibot.yml -e ${{env.schema}} -b ${{env.board}} -d ${{env.dir}} -s run_drc -v -i
  DRC:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad7_auto_full:latest
    steps:
      - uses: actions/checkout@v3
      - name: run kibot
        run: |
          kibot -c kibot.yml -e ${{env.schema}} -b ${{env.board}} -d ${{env.dir}} -s run_erc -v -i

# images
  render:
    runs-on: ubuntu-latest
    #needs: [DRC]  TODO: Enable this!
    container: ghcr.io/inti-cmnb/kicad7_auto_full:latest
    steps:
      - uses: actions/checkout@v3
      - name: run kibot
        run: |
          kibot -c kibot.yml -e ${{env.schema}} -b ${{env.board}} -d ${{env.dir}} -s run_erc,run_drc -v \
            oshpark_purple_png_top oshpark_purple_png_bottom render_3d_30deg blender_3d_30deg
      - uses: actions/upload-artifact@v3.1.1
        if: ${{success()}}
        with:
          name: ${{github.event.repository.name}}_img
          if-no-files-found: error
          path: |
            ${{env.dir}}/img/**
            !${{env.dir}}/**/*.ogv
            !${{env.dir}}/**/*.log

  docs:
    runs-on: ubuntu-latest
    #needs: [DRC]  TODO: Enable this!
    container: ghcr.io/inti-cmnb/kicad7_auto_full:latest
    steps:
      - uses: actions/checkout@v3
      - name: run kibot
        run: |
          kibot -c kibot.yml -e ${{env.schema}} -b ${{env.board}} -d ${{env.dir}} -s run_erc,run_drc -v \
            ibom_html bom_html bom_csv schematic_pdf
      - uses: actions/upload-artifact@v3.1.1
        if: ${{success()}}
        with:
          name: ${{github.event.repository.name}}_docs
          if-no-files-found: error
          path: |
            ${{env.dir}}/docs/**
            !${{env.dir}}/**/*.ogv
            !${{env.dir}}/**/*.log
